import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/home.module.css'

export default function Home() {

    return (
      <div className='{styles.container}'>

        <Head>
          <title>Kizukuと愉快な仲間たち</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='{styles.main}'>

          <Link href="/rooms">
            <p>ルーム一覧</p>
          </Link>

        </main>
        
      </div>
    )
    
}