import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/home.module.css'

export default function Home() {

    return (
      <div className='{styles.container}'>

         <Head>
          <title>Kizukuと愉快な仲間たち</title>
          <meta name="description" content="Generated by create next app" />
          <Link href="/rooms">
            <p>ルーム一覧</p>
         </Link>
          <link rel="icon" href="/favicon.ico" />
        </Head> 
        
        <main className='{styles.main}'>

          

          <h1 className="text-orange-500 text-3xl font-bold underline">
            this is tailwind
          </h1>

          <h1 className="text-cyan-500 text-3xl font-bold underline">
            this is naka no branch
          </h1>
        
          <div className="content">
          <div className="right">
            <div className="door"></div>
          </div>
          <div className="left">
            <div className="stairs">
              <div className="bars"></div>
            </div>
            <div className="nosferatu"></div>
          </div>
          <div className='cinema'>
            <div className="effect">
              <div className="grain"></div>
            </div>
          </div>
          </div>
        

        </main>
        
      </div>
      
    )
    
}